import React, { PropsWithChildren } from "react";

import Head from "next/head";

import { Header, MainContainer, BackButton } from "components";

import styles from "./styles.module.css";

export default function HomeLayout({ children }: PropsWithChildren) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{"Vertrical Coding Challenge"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />

      <MainContainer>{children}</MainContainer>
    </div>
  );
}
