import React, { useState, useRef, useContext } from "react";
import Head from "next/head";

import { StoreContext } from "context";

import { SearchField, Header, MainContainer } from "components";

import { SearchResults } from "./SearchResults";

import styles from "./styles.module.css";

export default function HomeScreen() {
  const [text, setText] = useState("");
  const element = useRef(null);

  const { state } = useContext<any>(StoreContext);
  const { moviesState } = state;
  const { movies } = moviesState;

  return (
    <div className={styles.container}>
      <Head>
        <title>Vertrical Coding Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <MainContainer>
        <div className={styles.searchSection}>
          <h3>Search Bar</h3>
          <SearchField text={text} setText={setText} />
        </div>

        <div className={styles.innerContainer}>
          <h3 ref={element} className={styles.resultTitle}>
            Results
          </h3>

          <SearchResults movies={movies} />
        </div>
      </MainContainer>
    </div>
  );
}
