export const dummyData = [
  {
    _id: "0",
    title: "title 1",
    photo: "photo",
    description: "description",
    shortDescription: "Short Description",
  },
  {
    _id: "1",
    title: "title 2",
    photo: "photo",
    description: "description",
    shortDescription: "Short Description",
  },
  {
    _id: "2",
    title: "title 3",
    photo: "photo",
    description: "description",
    shortDescription: "Short Description",
  },
  {
    _id: "3",
    title: "titlev4",
    photo: "photo",
    description: "description",
    shortDescription: "Short Description",
  },
  {
    _id: "4",
    title: "title 5",
    photo: "photo",
    description: "description",
    shortDescription: "Short Description",
  },
  {
    _id: "5",
    title: "title 6",
    photo: "photo",
    description: "description",
    shortDescription: "Short Description",
  },
  {
    _id: "6",
    title: "title 7",
    photo: "photo",
    description: "description",
    shortDescription: "Short Description",
  },
  {
    _id: "7",
    title: "title 8",
    photo: "photo",
    description: "description",
    shortDescription: "Short Description",
  },
  {
    _id: "8",
    title: "title 9",
    photo: "photo",
    description: "description",
    shortDescription: "Short Description",
  },
  {
    _id: "9",
    title: "title 10",
    photo: "photo",
    description: "description",
    shortDescription: "Short Description",
  },
  {
    _id: "10",
    title: "title 11",
    photo: "photo",
    description: "description",
    shortDescription: "Short Description",
  },
  {
    _id: "11",
    title: "title 12",
    photo: "photo",
    description: "description",
    shortDescription: "Short Description",
  },
];
